import XCTest
import AppKit
@testable import GoProStitcherKit

final class AVMetadataReaderTests: XCTestCase {

    // URL to the tiny valid MP4 fixture bundled with test resources.
    var validMP4URL: URL!
    // URL that points to a file that does not exist.
    let invalidURL = URL(fileURLWithPath: "/nonexistent/file.mp4")

    override func setUp() {
        super.setUp()
        // Bundle.module is generated by SPM for test targets with resources
        validMP4URL = Bundle.module.url(forResource: "GH010001", withExtension: "MP4")
        XCTAssertNotNil(validMP4URL, "GH010001.MP4 fixture must be present in test bundle Resources/")
    }

    override func tearDown() {
        validMP4URL = nil
        super.tearDown()
    }

    // MARK: - duration

    func testDurationValidFile() async throws {
        let duration = await AVMetadataReader.duration(url: validMP4URL)
        XCTAssertNotNil(duration, "Expected non-nil duration for a valid MP4")
        if let d = duration {
            XCTAssertGreaterThan(d, 0.0, "Expected duration > 0 for a valid MP4")
        }
    }

    func testDurationInvalidFile() async throws {
        let duration = await AVMetadataReader.duration(url: invalidURL)
        XCTAssertNil(duration, "Expected nil duration for a non-existent file")
    }

    // MARK: - resolution

    func testResolutionValidFile() async throws {
        let size = await AVMetadataReader.resolution(url: validMP4URL)
        XCTAssertNotNil(size, "Expected non-nil resolution for a valid MP4")
        if let s = size {
            XCTAssertGreaterThan(s.width, 0, "Expected width > 0")
            XCTAssertGreaterThan(s.height, 0, "Expected height > 0")
        }
    }

    func testResolutionInvalidFile() async throws {
        let size = await AVMetadataReader.resolution(url: invalidURL)
        XCTAssertNil(size, "Expected nil resolution for a non-existent file")
    }

    // MARK: - thumbnail

    func testThumbnailValidFile() async throws {
        let image = await AVMetadataReader.thumbnail(url: validMP4URL)
        XCTAssertNotNil(image, "Expected non-nil NSImage thumbnail for a valid MP4")
    }

    func testThumbnailInvalidFile() async throws {
        let image = await AVMetadataReader.thumbnail(url: invalidURL)
        XCTAssertNil(image, "Expected nil thumbnail for a non-existent file")
    }
}
